return PlaceObj('ModDef', {
	'title', "Final Stand",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 5,
		}),
	},
	'id', "bzoQECK",
	'author', "Soundwave2142",
	'version_minor', 50,
	'version', 815,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Common.lua",
		"Code/CampaignConfigDefs.lua",
		"Code/CampaignEffectDefs.lua",
		"Code/FactionDefs.lua",
		"Code/AppearanceDefs.lua",
		"Code/Appearance.lua",
		"Code/Start.lua",
		"Code/Main.lua",
		"Code/Final.lua",
		"Code/UIPresets.lua",
		"Code/UI.lua",
		"Code/Debugger.lua",
		"UnitData/TestF.lua",
		"UnitData/TestM.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1743775348,
	'code_hash', 8275633575255090762,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "CampaignPreset",
			'Id', "FinalStand",
			'ClassDisplayName', "Campaign",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandConfigDef",
			'Id', "Default",
			'ClassDisplayName', "Final Stand Config",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Mercs",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Militia",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "Militia",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Rebels",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "Rebels",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsLeader",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsMechanic",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsDoctor",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsExplosive",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsMarksmen",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsAllRounder",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "General",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralDoctor",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralExplosives",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralLeader",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralMarksmen",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralMechanic",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Legion",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Adonis",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Army",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "SuperSoldiers",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "ThreeWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "FiveWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "SevenWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "isFinalStand",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandSelected",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandBeforeUIInsert",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandUIInserted",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandUIRemoved",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandGameConfigured",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandWaveScheduled",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandAttackSquadSpawning",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandAppearanceOptionsLoaded",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandWaveEnded",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandRewardMoney",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandRewardXP",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandBobbyRayRestock",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandCampaignEnding",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "TestF",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "TestAppearanceF",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "TestM",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "TestAppearanceM",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "NewGameMenuFinalStandEntryOld",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "NewGameMenuFinalStandOld",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
	},
})