return PlaceObj('ModDef', {
	'title', "Final Stand",
	'description', "New campaign designed as a replayable survival gamemode. Every playthrough offers a unique experience through the decisions you make, the strategies you employ, and the tactics you use to survive.\n\nChoose your faction, an enemy faction, and a sector to defend. Assemble a squad of mercs and take your stance, fighting waves of enemies. Beating a wave will grant you XP, money, and some respite. Spend it wisely and prepare for the next wave, level up mercs, buy guns, gather supplies, and perform sector operations. Each wave will be tougher with better-equipped enemies and greater numbers. Beat them all in order to win.",
	'image', "Mod/FinalStand/Images/preview.png",
	'last_changes', "Initial version upload of the mod. For details about core mechanics in the base version, navigate to CHANGELOG.md",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.md",
		"*.bbcode",
		"*.drawio",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 5,
		}),
	},
	'id', "FinalStand",
	'author', "Soundwave2142",
	'version_minor', 80,
	'version', 601,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Common.lua",
		"Code/CampaignConfigDefs.lua",
		"Code/CampaignEffectDefs.lua",
		"Code/FactionDefs.lua",
		"Code/AppearanceDefs.lua",
		"Code/Appearance.lua",
		"Code/Start.lua",
		"Code/Main.lua",
		"Code/Final.lua",
		"Code/UIPresets.lua",
		"Code/UI.lua",
		"Code/Debugger.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1749380525,
	'code_hash', -3157340217198959374,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "CampaignPreset",
			'Id', "FinalStand",
			'ClassDisplayName', "Campaign",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandConfigDef",
			'Id', "Default",
			'ClassDisplayName', "Final Stand Config",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Mercs",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralLeader",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralMarksmen",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralAllRounder",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralExplosives",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralDoctor",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralMechanic",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Militia",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "MilitiaLeader",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "MilitiaMarksmen",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "MilitiaAllRounder",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "MilitiaExplosive",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "MilitiaDoctor",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "MilitiaMechanic",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Rebels",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsLeader",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsMarksmen",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsAllRounder",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsExplosive",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsDoctor",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "RebelsMechanic",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Legion",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Adonis",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Army",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "SuperSoldiers",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "ThreeWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "FiveWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "SevenWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "OperationProgressPerTick",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "OperationIsEnabled",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "isFinalStand",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandSelected",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandBeforeUIInsert",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandUIInserted",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandUIRemoved",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandGameConfigured",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandWaveScheduled",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandAttackSquadsPicked",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandAttackSquadsSpawning",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandAppearanceOptionsLoaded",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandWaveEnded",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandRewardMoney",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandRewardXP",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandBobbyRayRestock",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "FinalStandCampaignEnding",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandSectorDef",
			'Id', "H4",
			'ClassDisplayName', "Final Stand Sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandSectorDef",
			'Id', "I9",
			'ClassDisplayName', "Final Stand Sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandSectorDef",
			'Id', "L8",
			'ClassDisplayName', "Final Stand Sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandSectorDef",
			'Id', "D7",
			'ClassDisplayName', "Final Stand Sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandSectorDef",
			'Id', "D17",
			'ClassDisplayName', "Final Stand Sector",
		}),
	},
	'steam_id', "3495365172",
	'TagOther', true,
	'TagQuest&Campaigns', true,
})