return PlaceObj('ModDef', {
	'title', "Final Stand",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 5,
		}),
	},
	'id', "bzoQECK",
	'author', "Soundwave2142",
	'version_minor', 50,
	'version', 697,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Common.lua",
		"Code/CampaignConfigDefs.lua",
		"Code/CampaignEffectsDefs.lua",
		"Code/FactionDefs.lua",
		"Code/AppearanceDefs.lua",
		"Code/Appearance.lua",
		"Code/Start.lua",
		"Code/Main.lua",
		"Code/Final.lua",
		"Code/UIPresets.lua",
		"Code/UI.lua",
		"Code/Debugger.lua",
		"UnitData/TestF.lua",
		"UnitData/TestM.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1743244887,
	'code_hash', 6449214677327764613,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "CampaignPreset",
			'Id', "FinalStand",
			'ClassDisplayName', "Campaign",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandConfigDef",
			'Id', "Default",
			'ClassDisplayName', "Final Stand Config",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Mercs",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Militia",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Rebels",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Legion",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Adonis",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "Army",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandFriendlyFactionDef",
			'Id', "SuperSoldiers",
			'ClassDisplayName', "Final Stand Friendly Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "Rebels",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "Militia",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "SuperSoldiers",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "General",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralDoctor",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralExplosives",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralLeader",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralSniper",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandAttirePoolDef",
			'Id', "GeneralMechanic",
			'ClassDisplayName', "Final Stand Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Legion",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Adonis",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "Army",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandEnemyFactionDef",
			'Id', "SuperSoldiers",
			'ClassDisplayName', "Final Stand Enemy Faction",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "ThreeWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "FiveWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "FinalStandLengthDef",
			'Id', "SevenWaves",
			'ClassDisplayName', "Final Stand Length",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "TestF",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "TestAppearanceF",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "TestM",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "TestAppearanceM",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "NewGameMenuFinalStandEntryOld",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "NewGameMenuFinalStandOld",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
	},
})